version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
        mysql: 
          condition: service_healthy

  mysql:
    container_name: name
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: meta
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
